# Site settings
title: Global Statistical Pocket Book 2015
email: your-email@domain.com
description: "This is a temporary site for deploying draft versions of the pocket book"
baseurl: "http://muuankarski.github.io/GSPB15/"
url: "http://muuankarski.github.io/GSPB15/"
twitter_username: muuankarski
github_username:  muuankarski

# Build settings
markdown: kramdown
permalink: pretty
